#!/usr/bin/env bash

export MOTION_SCORE=30

export MOTION_CAMERA_ROTATION=0
export MOTION_CAMERA_SATURATION=20
export MOTION_CAMERA_SHARPNESS=20

export MOTION_NIGHT_MODE_ALLOWED="True"
export MOTION_NIGHT_MODE_START_H=19
export MOTION_NIGHT_MODE_START_M=30
export MOTION_NIGHT_MODE_END_H=5
export MOTION_NIGHT_MODE_END_M=30

export MOTION_LIVE_REFRESH_INTERVAL_SECONDS=5